spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: 'true'
    show-sql: 'true'
  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: '{cipher}33e3353d1004236c5a891541df2928fab7f3fe2475e1e9a2b73eac2511d8a01f'
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8082 
