spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: 'true'
    show-sql: 'true'
  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
server:
  port: 8081    